add support for LUD-19 for boltcards extension
lnbits/boltcards pull request #19
Opened 2023-09-13 20:48 UTC by gorrdy

LNURLw (withdrawRequest) that is returned by calling the link from bolt card now returns another field "payLink" as defined in LUD-19.

This allows compatible wallet to create e.g. refund or cashback to the card itself without need to create a separate invoice or managing another separate LNURLp or LN address.

2023-09-13 21:17 UTC, prusnak requested changes
small style nits

2023-09-13 21:17 UTC, prusnak commented on lnurl.py
> +        "payLink": lnurlpay_nonbech32_lud17, #LUD-19 compatibility
nitpick: style - two spaces before and one space after `#`
```suggestion
        "payLink": lnurlpay_nonbech32_lud17,  # LUD-19 compatibility
```

2023-09-13 21:17 UTC, prusnak commented on lnurl.py
> +    #the raw lnurl
nitpick: style - one space after `#`
```suggestion
    # the raw lnurl
```

2023-09-13 21:17 UTC, prusnak commented on lnurl.py
> +    #bech32 encoded lnurl
nitpick: style - one space after `#`
```suggestion
    # bech32 encoded lnurl
```

2023-09-13 21:17 UTC, prusnak commented on lnurl.py
> +    #create a lud17 lnurlp to support lud19, add to payLink field of the withdrawRequest
nitpick: style - one space after `#`
```suggestion
    # create a lud17 lnurlp to support lud19, add to payLink field of the withdrawRequest
```

2023-09-13 21:17 UTC, prusnak commented on lnurl.py
> +
drop one empty line
```suggestion
```

2023-09-14 03:13 UTC, gorrdy reviewed
applied some suggestion on code formatting. thanks @prusnak

2023-09-19 21:18 UTC, prusnak commented on lnurl.py
> +    lnurlpay_nonbech32_lud17 = lnurlpay_raw.replace("https://", "lnurlp://").replace("http://","lnurlp://")
I am wondering whether we need to perform this protocol conversion.

Wouldn't it work if we kept the original protocol (http/https)?

2023-09-19 21:31 UTC, gorrdy commented on lnurl.py
> +    lnurlpay_nonbech32_lud17 = lnurlpay_raw.replace("https://", "lnurlp://").replace("http://","lnurlp://")
LNURL can be either bech32 encoded or non bech32-encoded as specified in LUD-17.

So the wallet either expects bech32 encoded or LUD-17 non bech32-encoded.

LNURL starting with http or https is not specified afaik anywhere and it's not supported by any LN wallet. The LUD-17 prefixes can indicate a different usage. You don't want to open a lnurlc (channel request) LNURL in e.g. custodial lightning wallet like Bitlifi, Wallet of Satoshi etc. So if e.g. smartphone decides which app to open, lnurlp and lnurlw can be served to different apps then lnurlc or keyauth prefix.

Also the wallet doesn't have to support all the LUD-17 prefixes so it is handy to have the information that "This is a LNURLw or LNURLp" before you even do any request to the server instead of trying and then checkint the "tag" field.

2023-09-19 21:36 UTC, prusnak commented on lnurl.py
> +    lnurlpay_nonbech32_lud17 = lnurlpay_raw.replace("https://", "lnurlp://").replace("http://","lnurlp://")
OK. Right. LUD-17 says it clearly. Thanks!

2023-09-19 21:36 UTC, prusnak approved these changes

2023-09-20 00:13 UTC, iWarpBTC commented on lnurl.py
> +    lnurlpay_nonbech32_lud17 = lnurlpay_raw.replace("https://", "lnurlp://").replace("http://","lnurlp://")
I believe the lud17 prefixes make sense when the link stands on its own. They are pretty pointless inside a json reponse, when the payLink key clearly annouces a type of link (scheme).

2023-09-21 06:37 UTC, dni approved these changes

2023-09-21 06:37 UTC, merged

2023-09-25 11:48 UTC, arbadacarbaYK commented
LUD19 was about tap and top up. How is topping up handled now ? This needs a wiki entry.

2023-09-25 11:54 UTC, gorrdy commented
> LUD19 was about tap and top up. How is topping up handled now ? This needs a wiki entry.

I don't think the topping up is handled in LNbits anyhow. This PR just serves the payLink when tapping the bolt card. It depends on the wallet on the other side how it handles it.

In LNbits I would like a implementation in e.g. TPoS extension in LNbits. Also this extension (boltcards) could have some page that reads the NFC card withDraw link and if there is a payLink field, then show some dialog how many sats to top up. Not sure where this should be in UI.

2023-09-25 11:59 UTC, arbadacarbaYK commented
> > LUD19 was about tap and top up. How is topping up handled now ? This needs a wiki entry.
> 
> I don't think the topping up is handled in LNbits anyhow. This PR just serves the payLink when tapping the bolt card. It depends on the wallet on the other side how it handles it.
> 
> In LNbits I would like a implementation in e.g. TPoS extension in LNbits. Also this extension (boltcards) could have some page that reads the NFC card withDraw link and if there is a payLink field, then show some dialog how many sats to top up. Not sure where this should be in UI.

yes because we are waiting on the end of the discussion in the nfc mafia group how we want it. In the desc is not the way, cause it cannot be interpreted by the devices. 
Wouldve like to see the end of that first. So far only LUD21 changes for boltcard on tpos are near to ready. 

There also is a status page for boltcards that tal just made that should show this paylink.

This is just half of the story and the documentation is not handled also.